### ISSUE TITLE
Need Hero Image Por Favor

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Institute-for-Public-Affairs#4]
Hey Zac, we tried! The image just isn't working, can you whip up a stock one when you have a free moment? Thanks so much! 

![image](https://user-images.githubusercontent.com/15130721/46298931-4769f180-c56e-11e8-82ef-08c078c6679f.png)

**Comment by ZMcGroarty** [comment]
![ipa-min](https://user-images.githubusercontent.com/15017242/46299174-ca8b4780-c56e-11e8-8e70-4a589a2405fe.png)

**Comment by CVE82** [comment]
Thanks!!
