### ISSUE TITLE
News Feed not populating on homepage

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Institute-for-Public-Affairs#5]
The news feed is not populating on the homepage. The landing page, panel and news csv in Drupal are all set up correctly. If you can show me how to fix this, this can go live today. The Read Our Stories link is still going to the College News page instead of their IPA News Landing page.

**Comment by tu-chill** [comment]
the path to csv in views was institute-for-public-affairs, but in the repo, for program site, the config was looking at news/intitute-for-public-affairs/csv

**Comment by CVE82** [comment]
Ahh gothcha, do you know why it's still not populating? I have restarted the build a couple of times..

**Comment by CVE82** [comment]
The landing page and feed are both in there though... The view is right, I'm confused.. 

![image](https://user-images.githubusercontent.com/15130721/46356946-cbd17880-c631-11e8-9960-df5f2d07bbd1.png)

**Comment by tu-chill** [comment]
Still not sure what fixed it. This is crazy. I looked at all the spelling and took out any white space. Maybe I removed an unused dead bit of info. I'm sure we will run into this again. grrrr
